# Generated by Django 4.2.2 on 2023-07-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=45)),
                ('Event_Venue', models.CharField(max_length=100)),
                ('Event_Description', models.CharField(max_length=500)),
                ('Event_Date', models.DateField()),
                ('Event_Time', models.TimeField()),
                ('Event_AvailableTickets', models.IntegerField(max_length=45)),
            ],
        ),
    ]
